---
- hosts: all
- import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml

- name: include env-vars file
  include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import databse file
  import_playbook: ../static-assignement/db.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 