---
- hosts: uat-webservers
  name: Include dynamic variables 
  tasks:
    - import_playbook: ../static-assignments/common.yml 
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- hosts: uat-webservers
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml

- hosts: uat-webservers
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- hosts: uat-webservers
  tasks:
    - import_playbook: ../static-assignment/db.yml

- hosts: lb
  tasks:
    - import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 

