---
- hosts: uat-webservers
  name: Include dynamic variables and import common playbook
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always
    - import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
  name: Import uat-webservers playbook
  tasks:
    - import_playbook: ../static-assignments/uat-webservers.yml

- hosts: uat-webservers
  name: Include env-vars tasks
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- name: import database file
  import_playbook: ../static-assignments/db.yml

- hosts: lb
  name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required


