---
- hosts: uat-webservers
  name: Include dynamic variables
  tasks:
    - include_playbook: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- hosts: uat-webservers
  name: Import common and uat-webservers playbooks
  tasks:
    - import_playbook: ../static-assignments/common.yml
    - import_playbook: ../static-assignments/uat-webservers.yml

- name: import env-vars file
  hosts: uat-webservers
  include_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: import database file
  import_playbook: ../static-assignments/db.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
