# ---
# - hosts: uat-webservers
#   name: Include dynamic variables and import common playbook
#   tasks:
#     - include_tasks: ../dynamic-assignments/env-vars.yml
#       tags:
#         - always
#     - import_tasks: ../static-assignments/common.yml

# - hosts: uat-webservers
#   name: Import uat-webservers playbook
#   tasks:
#     - import_tasks: ../static-assignments/uat-webservers.yml

# - hosts: uat-webservers
#   name: Include env-vars tasks
#   tasks:
#     - include_tasks: ../dynamic-assignments/env-vars.yml
#       tags:
#         - always

# - name: database assignment
#   import_playbook: ../static-assignments/db.yml

# - hosts: lb
#   name: Loadbalancers assignment
#   tasks:
#     - import_tasks: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required

# - name: import webserber files
#   import_playbook: ../static-assignments/uat-webservers.yml

# - name: import loadbalancer assignments
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required

# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml

# - hosts: sonarqube
# - name: sonarqube
#   import_playbook: ../static-assignments/sonar.yml

- hosts: pre-prod
- name: pre-prod
  import_playbook: ../static-assignments/pre-prod.yml
